default: &postgresql
  adapter: postgresql
  port: 5432
  pool: 20
  timeout: 5000

default: &vulcain
  <<: *postgresql
  database: vulcain

development:
  <<: *vulcain
  database: vulcain_development
  host: localhost
  username: philippe
  password: 

test:
  <<: *vulcain
  database: vulcain_development
  host: localhost
  username: philippe
  password: 



