#!/usr/bin/env ruby
require 'json'

def products_urls vendor
  case vendor
  when "RueDuCommerce" then ["http://www.rueducommerce.fr/TV-Hifi-Home-Cinema/showdetl.cfm?product_id=4872804#xtor=AL-67-75%5Blien_catalogue%5D-120001%5Bzanox%5D-%5B1532882"]
  when "AmazonFrance" then ["http://www.amazon.fr/C%C3%A9line-Romans-2-Louis-Ferdinand/dp/2070107973/ref=pd_sim_b_2"]
  when "Fnac" then ["http://musique.fnac.com/a5377201/Depeche-Mode-Delta-machine-Edition-deluxe-CD-album#bl=HGMUblo1"]
  when "Cdiscount" then ["http://www.cdiscount.com/juniors/jeux-et-jouets-par-type/puzzle-cars-2-250-pieces/f-1200622-cle29633.html"]
  end
end

if ARGV[0] == "--assess"
  vendor = ARGV[1]
  `curl -X POST -H "Content-Type: application/json" -H "Accept: application/json"  -d'{"context":{"session":{"uuid":"#{vendor}","callback_url":"http://127.0.0.1:3000/shopelia"},"answers":[{"question_id":"1", "answer":"false"}]}}' localhost:3000/answers`
else
  ARGV.each do |vendor|
    email = "legrand_pierre_04@free.fr"
    products_urls = products_urls(vendor)
    context = {"context"=>{"account"=>{"login"=>"#{email}","password"=>"shopelia2013"},"session"=>{"uuid"=>"#{vendor}","callback_url"=>"http=>//127.0.0.1:3000/shopelia"},"order"=>{"products_urls"=>products_urls},"user"=>{"birthdate"=>{"day"=>1,"month"=>4,"year"=>1985},"gender"=>1,"address"=>{"address_1"=>"12 rue des lilas","address_2"=>"","additionnal_address"=>"","first_name"=>"Pierre","last_name"=>"Legrand","zip"=>"75019","city"=>"Paris","mobile_phone"=>"0634562345","land_phone"=>"0134562345","country"=>"France"}}},"vendor"=>"#{vendor}"}
    
    `curl -X POST -H "Content-Type: application/json" -H "Accept: application/json"  -d'#{context.to_json}' localhost:3000/orders`
  end
end
