#!/usr/bin/env ruby
require 'json'

def products_urls vendor
  case vendor
  when "RueDuCommerce" then ["http://ad.zanox.com/ppc/?19436175C242487251&ULP=%5B%5BTV-Hifi-Home-Cinema/showdetl.cfm?product_id=4898282%2523xtor%253dAL-67-75%255blien_catalogue%255d-120001%255bzanox%255d-%255bZXADSPACEID%255d%5D%5D#rueducommerce.fr"]
  when "AmazonFrance" then ["http://www.amazon.fr/C%C3%A9line-Romans-2-Louis-Ferdinand/dp/2070107973/ref=pd_sim_b_2"]
  when "Fnac" then ["http://ad.zanox.com/ppc/?25134383C1552684717T&ULP=[[video.fnac.com%2Fa1772597%2FLa-Belle-et-le-Clochard-Edition-simple-DVD-Zone-2]]"]
  when "Cdiscount" then ["http://www.cdiscount.com/juniors/jeux-et-jouets-par-type/puzzle-cars-2-250-pieces/f-1200622-cle29633.html"]
  when "EveilEtJeux" then ["http://www.eveiletjeux.com/brainbox-voyage-autour-du-monde/produit/122996#xtatc=INT-2151-||"]
  end
end

if ARGV[0] == "--assess"
  vendor = ARGV[1]
  `curl -X POST -H "Content-Type: application/json" -H "Accept: application/json"  -d'{"context":{"session":{"uuid":"#{vendor}","callback_url":"http://127.0.0.1:3000/shopelia"},"answers":[{"question_id":"1", "answer":"false"}]}}' localhost:3000/answers`
else
  ARGV.each do |vendor|
    email = "legrand_pierre_04@free.fr"
    product_url = products_urls(vendor).first
    context = {"context"=>{"account"=>{"login"=>"#{email}","password"=>"shopelia2013"},"session"=>{"uuid"=>"#{vendor}","callback_url"=>"http=>//127.0.0.1:3000/shopelia"},"order"=>{"credentials" =>{'holder'=>'PierrePetit','number'=>'501290129019201','exp_month'=>5,'exp_year'=>2014,'cvv'=>123}, "products"=>[{url:product_url, quantity:1}]},"user"=>{"birthdate"=>{"day"=>1,"month"=>4,"year"=>1985},"gender"=>1,"address"=>{"address_1"=>"12 rue des lilas","address_2"=>"","additionnal_address"=>"","first_name"=>"Pierre","last_name"=>"Legrand","zip"=>"75019","city"=>"Paris","mobile_phone"=>"0634562345","land_phone"=>"0134562345","country"=>"France"}}},"vendor"=>"#{vendor}"}
    
    `curl -X POST -H "Content-Type: application/json" -H "Accept: application/json"  -d'#{context.to_json}' localhost:3000/orders`
  end
end
