module RueDuCommerce
  SITE_URL = "http://m.rueducommerce.fr/"
  PASSWORD = "shopelia"
  
  MENU_BTN = ".//a[@class='menu-btn']"
  MY_ACCOUNT_LINK = ".//a[@title='Mon comte']"
  LOGINS_BUTTONS = ".//div[@class='login-buttons-container']//a"
  GENDER_M_RADIO = ".//input[@id='account_gender_M']"
  FIRSTNAME_INPUT = ".//input[@id='account_firstname']"
  LASTNAME_INPUT = ".//input[@id='account_lastname']"
  EMAIL_INPUT = ".//input[@id='account_email']"
  PASSWORD_INPUT = ".//input[@id='account_password']"
  CONFIRM_PASSWORD_INPUT = ".//input[@id='account_password_again']"
  FULL_ACCOUNT_SUBMIT_BUTTON = ".//input[@name='full-account']"
  ADDRESS_INPUT = ".//input[@id='account_address1']"
  CITY_INPUT = ".//input[@id='account_city']"
  POSTALCODE_INPUT = ".//input[@id='account_zip']"
  BIRTH_DAY_SELECT = ".//select[@id='account_birthdate_day']"
  BIRTH_MONTH_SELECT = ".//select[@id='account_birthdate_month']"
  BIRTH_YEAR_SELECT = ".//select[@id='account_birthdate_year']"
  SUBMIT_FORM = ".//input[@name='submit']"
  
  EMAIL_LOGIN_INPUT = ".//input[@id='login_email']"
  PASSWORD_LOGIN_INPUT = ".//input[@id='login_password']"
  LOGIN_SUBMIT_BUTTON = ".//div[@class='login-buttons-container']/input[@type='submit']"
  
  ADD_TO_CART_LINK = ".//section[@class='product-info']/a"
  CART_ACCESS_BUTTON = ".//input[@name='cart']"
  CART_LINKS = ".//div[@class='content-container']//a"
  ADDRESS_SUBMIT_BUTTON = ".//input[@class='green-btn-big']"
  VALIDATE_COLISSIMO = ".//input[@id='carrier-submit']"
  VISAS_IMAGE = ".//img[@name='PaymentMethod_ID_1']"
  VISA_IMAGE = ".//img[@src='/logo/mobile/VISA.png']"
  
  CARD_NUMBER_INPUT = ".//input[@name='CARD_NUMBER']"
  CRYPTO_INPUT = ".//input[@name='CVV_KEY']"
  CARD_VAL_MONTH_SELECT = ".//select[@name='CARD_VAL_MONTH']"
  CARD_VAL_YEAR_SELECT = ".//select[@name='CARD_VAL_YEAR']"
  PAYMENT_SUBMIT_BUTTON = ".//input[@name='PAIEMENT']"
  
end